services:
  db:
    image: postgres:17.2
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  web:
    build: .
    container_name: application
    restart: always
    volumes:
      - ./src:/app
      - ./entrypoint.sh:/app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: web-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/staticfiles:/app/staticfiles
    depends_on:
      - web
  
volumes:
  postgres_data: